--liquibase formatted sql
--changeset sampeteq:3

CREATE TABLE IF NOT EXISTS seat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_number INTEGER                                 NOT NULL,
    number     INTEGER                                 NOT NULL,
    hall_id    BIGINT,
    CONSTRAINT pk_hall_seat PRIMARY KEY (id),
    CONSTRAINT FK_HALL_SEAT_ON_HALL FOREIGN KEY (hall_id) REFERENCES hall (id)
);