--liquibase formatted sql
--changeset sampeteq:3

CREATE TABLE IF NOT EXISTS halls_seats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_number INTEGER                                 NOT NULL,
    number     INTEGER                                 NOT NULL,
    hall_id    BIGINT,
    CONSTRAINT pk_halls_seats PRIMARY KEY (id),
    CONSTRAINT FK_HALLS_SEATS_ON_HALL FOREIGN KEY (hall_id) REFERENCES halls (id)
);