--liquibase formatted sql
--changeset sampeteq:4

CREATE TABLE IF NOT EXISTS screenings
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date     TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    film_id  BIGINT,
    hall_id  BIGINT,
    CONSTRAINT pk_screenings PRIMARY KEY (id),
    CONSTRAINT FK_SCREENINGS_ON_FILM FOREIGN KEY (film_id) REFERENCES films (id),
    CONSTRAINT FK_SCREENINGS_ON_HALL FOREIGN KEY (hall_id) REFERENCES halls (id)
);