--liquibase formatted sql
--changeset sampeteq:5

CREATE TABLE IF NOT EXISTS screening_seat
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_free      BOOLEAN                                 NOT NULL,
    hall_seat_id BIGINT,
    screening_id BIGINT,
    version      INT,
    CONSTRAINT pk_screening_seat PRIMARY KEY (id),
    CONSTRAINT FK_SCREENING_SEAT_ON_HALL_SEAT FOREIGN KEY (hall_seat_id) REFERENCES hall_seat (id),
    CONSTRAINT FK_SCREENING_SEAT_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screening (id)
);