--liquibase formatted sql
--changeset sampeteq:5

CREATE TABLE IF NOT EXISTS screenings_seats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_free      BOOLEAN                                 NOT NULL,
    hall_seat_id BIGINT,
    screening_id BIGINT,
    CONSTRAINT pk_screenings_seats PRIMARY KEY (id),
    CONSTRAINT FK_SCREENINGS_SEATS_ON_HALL_SEAT FOREIGN KEY (hall_seat_id) REFERENCES halls_seats (id),
    CONSTRAINT FK_SCREENINGS_SEATS_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id)
);