--liquibase formatted sql
--changeset sampeteq:7

CREATE TABLE IF NOT EXISTS ticket
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT,
    screening_id BIGINT,
    row_number   INTEGER,
    number       INTEGER,
    user_id      BIGINT,
    CONSTRAINT pk_ticket PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screening (id),
    CONSTRAINT FK_TICKET_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id)
);