--liquibase formatted sql
--changeset sampeteq:7

CREATE TABLE IF NOT EXISTS ticket
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status       VARCHAR(255),
    version      BIGINT,
    screening_id BIGINT,
    seat_id      BIGINT,
    user_id      BIGINT,
    CONSTRAINT pk_ticket PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screening (id),
    CONSTRAINT FK_TICKET_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seat (id),
    CONSTRAINT FK_TICKET_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id)
);