--liquibase formatted sql
--changeset sampeteq:7

CREATE TABLE IF NOT EXISTS tickets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    screening_id BIGINT,
    seat_id      BIGINT,
    user_id      BIGINT,
    CONSTRAINT pk_tickets PRIMARY KEY (id),
    CONSTRAINT FK_TICKETS_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id),
    CONSTRAINT FK_TICKETS_ON_SEAT FOREIGN KEY (seat_id) REFERENCES screenings_seats (id),
    CONSTRAINT FK_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);