--liquibase formatted sql
--changeset sampeteq:8

CREATE TABLE mail
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject varchar NOT NULL,
    content varchar NOT NULL,
    sent_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_mail PRIMARY KEY (id),
    CONSTRAINT FK_MAIL_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id)
)