--liquibase formatted sql
--changeset sampeteq:1

CREATE TABLE IF NOT EXISTS BOOKINGS_SCREENINGS
(
    ID                         UUID PRIMARY KEY,
    TIME_TO_SCREENING_IN_HOURS INT
);

CREATE TABLE IF NOT EXISTS BOOKINGS_SEATS
(
    ID           UUID PRIMARY KEY,
    IS_AVAILABLE BOOLEAN,
    SCREENING_ID UUID,
    FOREIGN KEY (SCREENING_ID) REFERENCES BOOKINGS_SCREENINGS (ID)
);